import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Hashtable;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.AbstractDocument;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DynamicPlotter.java
 *
 * Created on Oct 18, 2011, 6:07:14 PM
 */
/**
 *
 * @author Ahsan
 */
public class DynamicPlotter extends javax.swing.JFrame
{

	 UserPoints userPoints;
	 DoubleFilter fieldFilter = new DoubleFilter();
	 PlotTable table;
	 int lastChosenColorIndex;
	 Color lastChosenColor = Color.black;
	 Hashtable<Object, Color> buttonToColourMap = new Hashtable<Object, Color>();
	 Color valueFieldDefaultColor = new Color(230, 230, 230);
	 JLabel placeHolder = new JLabel("x, y");
	 int currentPointRadius = 5;
	 UserLegend list;
	 UIUtils uiUtils;

	 String curveTypes [] = new String [] {"Linear", "Quadratic", "Cubic"};
	 
	 PlotPanel plotP;
	 /** Creates new form DynamicPlotter */
	 public DynamicPlotter()
	 {
		  System.setProperty("apple.laf.useScreenMenuBar", "true");
		  
		  try
		  {
			   // Set System L&F
			   UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
			  // UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
			   // UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");

		  }
		  catch (UnsupportedLookAndFeelException e)
		  {
			   // handle exception
		  }
		  catch (ClassNotFoundException e)
		  {
			   // handle exception
		  }
		  catch (InstantiationException e)
		  {
			   // handle exception
		  }
		  catch (IllegalAccessException e)
		  {
			   // handle exception
		  }
		  userPoints = new UserPoints();
		  initComponents();

                  list = new UserLegend(this, false);

                  table = new PlotTable(this, false, userPoints);

                  buttonToColourMap.put(colorComboBox.getItemAt(0), Color.black);
		  buttonToColourMap.put(colorComboBox.getItemAt(1), Color.red);
		  buttonToColourMap.put(colorComboBox.getItemAt(2), Color.green);
		  buttonToColourMap.put(colorComboBox.getItemAt(3), Color.blue);
		  lastChosenColorIndex = 0;
		  
		  
		  placeHolder.setForeground(Color.LIGHT_GRAY);
		  placeHolder.setFont(userCoordinateField.getFont());
		  userCoordinateField.setLayout(new BorderLayout());
		  userCoordinateField.add(placeHolder);

		  plotPanel.requestFocus();
		  
		  uiUtils = new UIUtils (this);
		  //radiusSpinner.setEditable(false);
		  
		  plotP = (PlotPanel)plotPanel;
	 }

	 /** This method is called from within the constructor to
	  * initialize the form.
	  * WARNING: Do NOT modify this code. The content of this method is
	  * always regenerated by the Form Editor.
	  */
	 @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pointColourGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        plotPanel = new PlotPanel (userPoints, 5);
        jPanel5 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userCoordinateField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        colorComboBox = new javax.swing.JComboBox();
        plotPointButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        pointRadiusMenuItem = new javax.swing.JMenuItem();
        curveTypeMenuItem = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        viewMenu = new javax.swing.JMenu();
        showPointsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph Plotter");
        setMinimumSize(new java.awt.Dimension(400, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResized(evt);
            }
        });

        plotPanel.setBackground(new java.awt.Color(255, 255, 255));
        plotPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        plotPanel.setMaximumSize(null);
        plotPanel.setPreferredSize(new java.awt.Dimension(565, 474));

        javax.swing.GroupLayout plotPanelLayout = new javax.swing.GroupLayout(plotPanel);
        plotPanel.setLayout(plotPanelLayout);
        plotPanelLayout.setHorizontalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        plotPanelLayout.setVerticalGroup(
            plotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        jToolBar1.setBackground(null);
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(739, 178));

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 32767));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 175));

        jLabel1.setText("Enter coordinate");

        ((AbstractDocument)userCoordinateField.getDocument()).setDocumentFilter(fieldFilter);
        userCoordinateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEnteredPoint(evt);
            }
        });
        userCoordinateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userCoordinateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userCoordinateFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(userCoordinateField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userCoordinateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel2);

        jPanel6.setBackground(null);
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(615, 175));

        jLabel3.setText("Colour:");

        colorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Red", "Green", "Blue", "Custom" }));
        colorComboBox.setMinimumSize(new java.awt.Dimension(61, 22));
        colorComboBox.setPreferredSize(new java.awt.Dimension(61, 21));
        colorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorComboBoxActionPerformed(evt);
            }
        });

        plotPointButton.setText("+");
        plotPointButton.setMaximumSize(new java.awt.Dimension(41, 20));
        plotPointButton.setMinimumSize(new java.awt.Dimension(41, 20));
        plotPointButton.setPreferredSize(new java.awt.Dimension(48, 23));
        plotPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEnteredPoint(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(colorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plotPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plotPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open");
        fileMenu.add(jMenuItem2);
        fileMenu.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Save");
        fileMenu.add(jMenuItem1);

        mainMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        pointRadiusMenuItem.setText("Point Radius");
        pointRadiusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointRadiusMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pointRadiusMenuItem);

        curveTypeMenuItem.setText("Curve Type");
        curveTypeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curveTypeMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(curveTypeMenuItem);

        jCheckBoxMenuItem1.setText("Enable Auto Legend");
        editMenu.add(jCheckBoxMenuItem1);

        mainMenuBar.add(editMenu);

        viewMenu.setText("View");

        showPointsMenuItem.setText("Show Points in Table");
        showPointsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPointsMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(showPointsMenuItem);

        mainMenuBar.add(viewMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userEnteredPoint(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userEnteredPoint
    {//GEN-HEADEREND:event_userEnteredPoint

		String str1 = userCoordinateField.getText();

		try
		{
			 userPoints.addPoint(str1, lastChosenColor);
			 ((PlotPanel) plotPanel).refresh();
			 userCoordinateField.setText("");
		}
		catch (IllegalArgumentException iae)
		{
			 JOptionPane.showMessageDialog(this, iae.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}


		table.refresh();
    }//GEN-LAST:event_userEnteredPoint

	 private void windowResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_windowResized
	 {//GEN-HEADEREND:event_windowResized

		  (plotP).refresh();
	 }//GEN-LAST:event_windowResized

         private void showPointsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPointsMenuItemActionPerformed

			table.setVisible(true);

         }//GEN-LAST:event_showPointsMenuItemActionPerformed

	 private void colorComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_colorComboBoxActionPerformed
	 {//GEN-HEADEREND:event_colorComboBoxActionPerformed
		  Color selectedColor = buttonToColourMap.get(colorComboBox.getSelectedItem());

		  if (selectedColor == null)
		  {
			   Color selectedFromChooser = JColorChooser.showDialog(this, "Pick a color", lastChosenColor);

			   if (selectedFromChooser == null)
			   {
				    colorComboBox.setSelectedIndex(lastChosenColorIndex);
				    return;
			   }
		  }

                  list.add(selectedColor);

		  lastChosenColor = selectedColor;
		  lastChosenColorIndex = colorComboBox.getSelectedIndex();
	 }//GEN-LAST:event_colorComboBoxActionPerformed

	 private void userCoordinateFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_userCoordinateFieldFocusGained
	 {//GEN-HEADEREND:event_userCoordinateFieldFocusGained
		  String currentValue = userCoordinateField.getText();
		  if (currentValue.length() == 0)
		  {

			   userCoordinateField.removeAll();
			   userCoordinateField.repaint();
		  }
	 }//GEN-LAST:event_userCoordinateFieldFocusGained

	 private void userCoordinateFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_userCoordinateFieldFocusLost
	 {//GEN-HEADEREND:event_userCoordinateFieldFocusLost
		  String currentValue = userCoordinateField.getText();

		  if (currentValue.length() == 0)
		  {
			   userCoordinateField.add(placeHolder);
			   userCoordinateField.repaint();
		  }
	 }//GEN-LAST:event_userCoordinateFieldFocusLost

	 private void pointRadiusMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pointRadiusMenuItemActionPerformed
	 {//GEN-HEADEREND:event_pointRadiusMenuItemActionPerformed
		 
		  PlotPanel converted = (PlotPanel) plotPanel;
		  int radius = uiUtils.getRadiusVal(converted.getPointRadius());
		  System.out.println (radius);
		  converted.setPointRadius(radius);
		  converted.refresh();
		 
		 
	 }//GEN-LAST:event_pointRadiusMenuItemActionPerformed

	 private void curveTypeMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_curveTypeMenuItemActionPerformed
	 {//GEN-HEADEREND:event_curveTypeMenuItemActionPerformed
		  plotP.setDegree(uiUtils.getCurve(plotP.getDegree(), userPoints.size() - 1));
		  plotP.refresh();
	 }//GEN-LAST:event_curveTypeMenuItemActionPerformed

	 /**
	  * @param args the command line arguments
	  */
	 public static void main(String args[])
	 {
		  java.awt.EventQueue.invokeLater(new Runnable()
		  {

			   public void run()
			   {
				    new DynamicPlotter().setVisible(true);
			   }
		  });
	 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox colorComboBox;
    private javax.swing.JMenuItem curveTypeMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel plotPanel;
    private javax.swing.JButton plotPointButton;
    private javax.swing.ButtonGroup pointColourGroup;
    private javax.swing.JMenuItem pointRadiusMenuItem;
    private javax.swing.JMenuItem showPointsMenuItem;
    private javax.swing.JTextField userCoordinateField;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
