import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlotPanel.java
 *
 * Created on Oct 18, 2011, 6:19:58 PM
 */
/**
 *
 * @author Ahsan
 */
public class PlotPanel extends javax.swing.JPanel
{

	 UserPoints pointsList;
	 private GraphRenderingEngine gi;

	 /** Creates new form PlotPanel */
	 public PlotPanel(UserPoints up, int pointRadius)
	 {
		  initComponents();

		  this.pointsList = up;
		  gi = new GraphRenderingEngine(up, pointRadius);
	 }

	 public void refresh()
	 {
		  repaint();
	 }
	 
	 public int getPointRadius()
	 {
		  return gi.getPointRadius();
	 }
	 
	  public void setPointRadius(int radius)
	 {
		  gi.setPointRadius(radius);
	 }
	  
	  public void setDegree (int degree)
	  {
		  gi.setDegree(degree);
	  }
	  
	  public int getDegree ()
	  {
		  return gi.getDegree();
	  }

	 /** This method is called from within the constructor to
	  * initialize the form.
	  * WARNING: Do NOT modify this code. The content of this method is
	  * always regenerated by the Form Editor.
	  */
	 @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

	 public void paintComponent(Graphics g)
	 {
		  super.paintComponent(g);

		  ((Graphics2D) g).setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

		  gi.renderImage(getWidth(), getHeight(), (Graphics2D) g);
	 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
