import java.util.Comparator;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserPointsTable.java
 *
 * Created on Oct 21, 2011, 1:15:49 PM
 */
/**
 *
 * @author ahraza
 */
public class PlotTable extends javax.swing.JDialog
{

	 UserPoints userPoints;
	 PointsTableModel tableModel = new PointsTableModel();

	 /** Creates new form UserPointsTable */
	 public PlotTable(java.awt.Frame parent, boolean modal, UserPoints up)
	 {
		  super(parent, "List of Points", modal);
		  initComponents();
		  this.userPoints = up;
		  pointsTable.setModel(tableModel);

		  TableRowSorter trs = new TableRowSorter(tableModel);
		  ColComparator c = new ColComparator();
		  trs.setComparator(1, c);
		  trs.setComparator(0, c);
		  pointsTable.setRowSorter(trs);


		  JTableHeader header = pointsTable.getTableHeader();
		  header.setUpdateTableInRealTime(true);
		  header.setReorderingAllowed(true);
	 }

	 /** This method is called from within the constructor to
	  * initialize the form.
	  * WARNING: Do NOT modify this code. The content of this method is
	  * always regenerated by the Form Editor.
	  */
	 @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pointsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));

        pointsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(pointsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	 /**
	  * @param args the command line arguments
	  */
	 private class PointsTableModel extends AbstractTableModel
	 {

		  public int getRowCount()
		  {
			   return userPoints.size();
		  }

		  public int getColumnCount()
		  {
			   return 2;
		  }

		  public Double getValueAt(int rowIndex, int columnIndex)
		  {
			   UserPoint point = userPoints.getPoint(rowIndex);
			   if (columnIndex == 0)
			   {
				    return point.x;
			   }
			   else
			   {
				    return point.y;
			   }
		  }

		  public boolean isCellEditable(int row, int col)
		  {
			   return false;
		  }

		  public String getColumnName(int index)
		  {
			   if (index == 0)
			   {
				    return "X Values";
			   }
			   else
			   {
				    return "Y Values";
			   }
		  }
	 }

	 private class ColComparator implements Comparator<Double>
	 {

		  public int compare(Double o1, Double o2)
		  {
			   return o1.compareTo(o2);
		  }
	 }

	 public void refresh()
	 {
		  tableModel.fireTableDataChanged();
	 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pointsTable;
    // End of variables declaration//GEN-END:variables
}
